### ISSUE TITLE
CLI support?

### ISSUE THREAD

**Issue by stevemao** [kentcdodds/webpack-validator-DEPRECATED#5]
```
npm install -g webpack-validator
webpack-validator webpack.config.js
Valid!
```

**Comment by kentcdodds** [comment]
Great idea! Would you like to [makeapullrequest.com](http://makeapullrequest.com)?

**Comment by nyrosmith** [comment]
I am reading https://leanpub.com/theclibook ATM and would love to make a PR when I am done.
If you can wait a few days I am in!

**Comment by kentcdodds** [comment]
Cool! I'm sure it can wait a bit. Please let me know what you're thinking about doing before you start so we can talk about what kind of implementation we want.

**Comment by nyrosmith** [comment]
@kentcdodds  I'd like to create a repo for fiddling around the cli-tool and to have a discussion basis. Is this ok for you?

**Comment by kentcdodds** [comment]
>  I'd like to create a repo for fiddling around the cli-tool and to have a discussion basis. Is this ok for you?

Totally!

> I have no idea how to get the result of the validations printed to the console :(

Yeah, right now the configuration-validator module itself does the logging. It should work just fine as you're using it though... I'll be able to give more direction soonish hopefully.

**Comment by nyrosmith** [comment]
@kentcdodds any news about this?

**Comment by kentcdodds** [comment]
Got a few things on my plate today. Will hopefully get to it tonight though. It's in my inbox.

![netflix-full-house-fuller-3ornjKEREhVsOmQG1q](https://camo.githubusercontent.com/3b63e1d20b6849c3c5deaa62367161c4aceacd86/68747470733a2f2f6d65646961302e67697068792e636f6d2f6d656469612f336f726e6a4b4552456856734f6d514731712f67697068792e676966)

**Comment by nyrosmith** [comment]
No problem & sorry for my eagerness. Just planning my "webpack-validator" evening for tomorrow. Home alone ;)

**Comment by xjamundx** [comment]
command line already supported!

Just add this to your package.json file under scripts:

` "validate": "node -e 'require(\"webpack-validator\")(require(\"./webpack.config.js\"))'",`

And then call `npm run validate`

Or call this directly:

`node -e "require('webpack-validator')(require('./webpack.config.js'))"`

**Comment by kentcdodds** [comment]
Oh snap
![reaction-13ywUiX9SwSlGM](https://camo.githubusercontent.com/6f26780cfa1f83ebc09e2c94a02672f51c365258/68747470733a2f2f6d65646961322e67697068792e636f6d2f6d656469612f31337977556958395377536c474d2f67697068792e676966)

**Comment by nyrosmith** [comment]
Maybe I am just too stupid. @xjamundx can you explain why my solution doesnot print to the console? And why call node inside a Node application?

**Comment by kentcdodds** [comment]
> can you explain why my solution doesnot print to the console

@nyrosmith, I'm not sure why your solution's not priting to the console.

> why call node inside a Node application

Actually, he's suggesting that you do this via the command line, not in a node application/code :-)

**Comment by nyrosmith** [comment]
I understand. But making this direct via cli eliminates lots of possibilities eg nice output of what went wrong, defining configs via regex, ...
I'd like to make it more user friendly like npm or git cli

**Comment by xjamundx** [comment]
@nyrosmith this definitely isn't a final best solution, but if you just need something in the short term that will work :)

**Comment by nyrosmith** [comment]
Ok, I fiddled around and got it working. The problem of getting no console output was just because if validation succeeds there is nothing but silence...

I had to make the following changes: 

- _configuration-validator_ returns an object {errors, warnings, config} so we know what happened. I also removed the configName prop bc I think the only output should be the warnings & errors. All other output should be provided by the consuming code.
- _webpack-validator_ returns the result object from _configuration-validator_
- The CLI gets the validation result and can provide nice messages

I changed the sources locally and included the dist output to folders of my playground.
@kentcdodds Is it ok if I change _configuration-validator_ & _webpack-validator_ to this behavior?

**Comment by nyrosmith** [comment]
@kentcdodds Can we make it this way? If yes I would make the appropriate PRs to both repos.

**Comment by kentcdodds** [comment]
> configuration-validator returns an object {errors, warnings, config} so we know what happened

:+1:

> I also removed the configName prop

Not sure what you mean, but let's see the diff :+1: 

> webpack-validator returns the result object from configuration-validator

That wouldn't allow me to do:

```javascript
module.exports = validateWebpack(config)
```

in my webpack config, which was kind of my original use case, but I think it's acceptable to change that to:

```javascript
validateWebpack(config)
module.exports = config
```

So we're good to discuss that.

> The CLI gets the validation result and can provide nice messages

Not sure what you'd be changing here, but let's see it!

> Is it ok if I change configuration-validator & webpack-validator to this behavior?

Let's see a diff in a pull request. I think that's :+1:

Thanks!

**Comment by xjamundx** [comment]
@nyrosmith I think you also want to add proper exit codes, because then you could do something like this, which will only show \"webpack validated" on success

```
node -e 'require(\"webpack-validator\")(require(\"./webpack.config.js\"))' && echo \"webpack validated\"
```

**Comment by nyrosmith** [comment]
@xjamundx of course. But for my playground I just ignored them.

**Comment by jonathanewerner** [comment]
I'd suggest that setting an On Hold tag should always imply adding a comment *what* is holding up the task.

**Comment by nyrosmith** [comment]
Sorry for Delay. Weekends belong to the family.
Implementing the CLI is on hold until configuration-validator gets its new API.

**Comment by jonathanewerner** [comment]
No stress. My weekends are the only part of the week were I have time for OSS stuff, so i'll be only active from Fri-Sun.  Shiftwork. :)
